name: Scrap Strategic Data

on:
  schedule:
    - cron: '0 3 * * 1'  # todos los lunes a las 03:00 UTC
  workflow_dispatch:     # también lo puedes correr manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scripts/scrapeCommanders.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/minibuses.json
          git commit -m "chore: update minibuses data [auto]" || echo "No changes to commit"
          git push
